### ISSUE TITLE
Would it be possible to set a preset and define a custom setting at the same time?

### ISSUE THREAD

**Issue by banglashi** [arillo/silverstripe-arbitrarysettings#2]

**Comment by bumbus** [comment]
Hi, I am not sure, what you want to achive, but there are the function include and exclude in `SettingsField`, maybe they do the job?
https://github.com/arillo/silverstripe-arbitrarysettings/blob/master/src/SettingsField.php#L83
https://github.com/arillo/silverstripe-arbitrarysettings/blob/master/src/SettingsField.php#L101
